Repository phineasla/4.1-React-Karma-BE, pull requests merged in 2023-01, with the labels that each got.

#11 Deposit to HCMUSBank add client endpoint
  package.json
  pnpm-lock.yaml
  prisma/schema.prisma
  src/all-exception.filter.ts
  src/error.ts
  src/external/dto/find-one-account.dto.ts
  src/external/dto/transfer.dto.ts
  src/external/external.controller.ts
  src/external/external.module.ts
  src/external/external.service.ts
  src/external/hcmusbank/hcmusbank.service.ts
  src/main.ts
  src/transactions/dto/create-external-transaction.dto.ts
  src/transactions/transactionOtp.service.ts
  src/transactions/transactions.module.ts
  src/transactions/transactions.service.ts
Labels: enhancement

#10 Enhance-get-all-interbank-transactions-with-pagination
  src/interbank/dto/query.dto.ts
  src/interbank/interbank.controller.ts
  src/interbank/interbank.service.ts
Labels: enhancement

#12 Swagger
  package.json
  pnpm-lock.yaml
  src/bankers/bankers.controller.ts
  src/bankers/dto/banker.response.dto.ts
  src/bankers/dto/create-banker.dto.ts
  src/bankers/dto/recharge.dto.ts
  src/bankers/dto/update-banker.dto.ts
  src/external/dto/find-one-external.dto.ts
  src/external/dto/transfer.dto.ts
  src/external/external.controller.ts
  src/external/hcmusbank/dto/find-one-account-response.dto.ts
  src/external/hcmusbank/dto/transfer.dto.ts
  src/interbank/dto/query.dto.ts
  src/interbank/interbank.controller.ts
  src/main.ts
  src/pagination/pagination.dto.ts
  src/transactions/dto/request-transaction.dto.ts
  src/transactions/dto/transactions.query.dto.ts
  src/transactions/transactions.controller.ts
  src/users/dto/create-user.dto.ts
  src/users/dto/update-user.dto.ts
  src/users/users.controller.ts
Labels: documentation

#16 Update swagger
  src/app.controller.ts
  src/app.module.ts
  src/app.service.ts
  src/bankers/bankers.controller.ts
  src/clients/clients.controller.ts
  src/clients/clients.module.ts
  src/clients/clients.service.ts
  src/clients/dto/client.response.dto.ts
  src/clients/dto/create-client.dto.ts
  src/clients/dto/update-client.dto.ts
  src/external/dto/find-one-external.dto.ts
  src/external/dto/transfer.dto.ts
  src/external/external.controller.ts
  src/external/hcmusbank/dto/find-one-account-response.dto.ts
  src/interbank/dto/interbank.response.dto.ts
  src/interbank/interbank.controller.ts
  src/transactions/dto/transaction.response.dto.ts
  src/transactions/transactionEmail.service.ts
  src/transactions/transactions.controller.ts
  src/transactions/transactions.module.ts
  src/users/users.controller.ts
  src/users/users.module.ts
Labels: documentation

#18 Fix balance not decreasing/increasing after external/local transfer
  src/external/external.service.ts
  src/paymentAccounts/dto/update-balance.dto.ts
  src/paymentAccounts/paymentAccounts.service.ts
  src/transactions/transactionOtp.service.ts
  src/transactions/transactions.service.ts
  src/user/user.controller.ts
  src/user/user.service.ts
Labels: bug

#20 CRUD "/user/contacts"
  prisma/schema.prisma
  src/clients/clients.controller.ts
  src/jwt/jwt.decorator.ts
  src/jwt/jwt.dto.ts
  src/paymentAccounts/paymentAccounts.controller.ts
  src/swagger/swagger.decorator.ts
  src/user/contacts/contacts.controller.ts
  src/user/contacts/contacts.module.ts
  src/user/contacts/contacts.service.ts
  src/user/contacts/dto/contact.response.dto.ts
  src/user/contacts/dto/create-contact.dto.ts
  src/user/contacts/dto/find-one-contact.dto.ts
  src/user/contacts/dto/update-contact.dto.ts
  src/user/contacts/entities/saved-list.entity.ts
  src/user/user.module.ts
Labels: enhancement

#25 External bank transfer
  .env.template
  src/app.module.ts
  src/constants.ts
  src/cryptography/cryptography.module.ts
  src/cryptography/cryptography.service.ts
  src/interbank/dto/interbank.request.dto.ts
  src/interbank/dto/transfer.dto.ts
  src/interbank/interbank.controller.ts
  src/interbank/interbank.service.ts
  src/paymentAccounts/paymentAccounts.service.ts
Labels: enhancement

#26 CRUD reminder
  prisma/schema.prisma
  src/external/hcmusbank/hcmusbank.service.ts
  src/pagination/pagination.utils.ts
  src/paymentAccounts/paymentAccounts.service.ts
  src/user/contacts/contacts.controller.ts
  src/user/contacts/contacts.module.ts
  src/user/contacts/contacts.service.ts
  src/user/reminders/dto/cancel-reminder.dto.ts
  src/user/reminders/dto/confirm-reminder.dto.ts
  src/user/reminders/dto/create-reminder.dto.ts
  src/user/reminders/dto/find-reminders.dto.ts
  src/user/reminders/entities/reminder.entity.ts
  src/user/reminders/reminders.controller.ts
  src/user/reminders/reminders.service.ts
  src/user/user.module.ts
  src/user/user.service.ts
Labels: enhancement

#27 Realtime notification
  src/app.module.ts
  src/constants.ts
  src/main.ts
  src/notification/entities/notification.entity.ts
  src/notification/events/reminder-created.event.ts
  src/notification/notification.gateway.ts
  src/notification/notification.module.ts
  src/socket.adapter.ts
  src/user/reminders/reminders.service.ts
  src/user/user.module.ts
Labels: enhancement

#30 Reminder now forces sender to use payID
  prisma/schema.prisma
  src/user/reminders/dto/confirm-reminder.dto.ts
  src/user/reminders/dto/create-reminder.dto.ts
  src/user/reminders/entities/reminder.entity.ts
  src/user/reminders/reminders.service.ts
Labels: enhancement

#32 Use HTML for email
  package.json
  pnpm-lock.yaml
  src/email/email.service.ts
  src/transactions/transactionEmail.service.ts
  src/transactions/transactions.controller.ts
  template/confirm-transaction/index.html
Labels: enhancement
